name: cocina_escolar
description: "Aplicación de control de vajilla y utensilios para cocina escolar."
publish_to: 'none' # Evita la publicación accidental en pub.dev.

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Librerías utilizadas en la aplicación
  cupertino_icons: ^1.0.8
  http: ^1.2.2                  # Para las peticiones al Backend Node.js
  mobile_scanner: ^5.1.1        # Para el escaneo de códigos de barras / QR con la cámara
  google_fonts: ^6.2.1          # Para la tipografía estilizada (Poppins)
  fl_chart: ^0.69.0             # <--- Obligatorio para las gráficas estadísticas (Pastel / Guía 7)

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Si tienes activos locales (como imágenes o iconos personalizados), puedes declararlos aquí abajo:
  # assets:
  #   - assets/
